### ISSUE TITLE
Ik zie heel veel kleuren, misschien een :root aanmaken en custom properties gebruiken

### ISSUE THREAD

**Issue by ppijn** [Sophievanderburg/serverside-get-inspired#6]
https://github.com/Sophievanderburg/serverside-get-inspired/blob/bf9ef3975d8071688be22bcde52507eafd677069/public/styles/style.css#L15

**Comment by Sophievanderburg** [comment]
Goede tip, maar voor nu vind ik dit fijner werken. :)
